# DataSource Configuration
spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-so-portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres-so-portal
    locations: classpath:db/migration
    user: postgres
    password: postgres
    baseline-on-migrate: true
    clean-disabled: false

axon:
  serializer:
    ## xstream is not compatible anymore with jdk17+
    general: jackson
  axonserver:
    enabled: false

boond:
  api:
    base-url: http://localhost:8089/api/v1  # Point to WireMock
    token: Bearer mock_token_123

wiremock:
  port: 8089

logging:
  level:
    boond: DEBUG
    com.github.tomakehurst.wiremock: INFO

#axoniq:
#  console:
#    application-name: Awesome-Microservice
#    credentials: <token> #https://console.axoniq.io/
#    dlq-mode: NONE

application:
  debug:
    enabled: true
